version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_em
    ports:
      - "5432:5432"
    networks:
      - app_network

  action-history-service:
    build:
      context: ./services/action-history-service
      dockerfile: .docker/Dockerfile
    depends_on:
      - postgres
    networks:
      - app_network
    env_file:
      - ./services/action-history-service/.env
    volumes:
      - ./services/action-history-service/src:/opt/app/src
    command:
      - npm
      - run
      - dev

  inventory-service:
    build:
      context: ./services/inventory-service
      dockerfile: .docker/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./services/inventory-service/src:/opt/app/src
    networks:
      - app_network
    env_file:
      - ./services/inventory-service/.env
    command:
      - npm
      - run
      - dev

  gateway:
    build:
      context: ./services/gateway
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      INVENTORY_SERVICE_URL: 'http://inventory-service:3000'
      ACTION_HISTORY_SERVICE_URL: 'http://action-history-service:3000'
    depends_on:
      - action-history-service
      - inventory-service
    networks:
      - app_network
    volumes:
      - ./services/gateway/src:/opt/app/src
    env_file:
      - ./services/gateway/.env
    command:
      - npm
      - run
      - dev

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
#      config:
#        - subnet: 192.168.1.0/24
