version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_em
    ports:
      - "5432:5432"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  action-history-service:
    build:
      context: ./services/action-history-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  inventory-service:
    build:
      context: ./services/inventory-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  gateway:
    build:
      context: ./services/gateway
    ports:
      - "3002:3002"
    depends_on:
      - action-history-service
      - inventory-service
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge